In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import pipeline,preprocessing,metrics,model_selection,ensemble
from sklearn.externals import joblib

In [9]:
# Importing the dataset
dataset = pd.read_csv('SalesData.csv')
X = dataset.iloc[:, 1:2].values
y = dataset.iloc[:, 6:7].values


In [10]:
dataset.head()

StoreID  Week Week_start   Week_end  Count  Sum_Gross Margin  Sum_Sales  \
0    10018     1   2/6/2015  2/12/2015    552           2213.39    4741.48   
1    10018     2  2/13/2015  2/19/2015    542           2164.69    4571.25   
2    10018     3  2/20/2015  2/26/2015    378           1561.42    3348.25   
3    10018     4  2/27/2015   3/5/2015    576           2343.62    5114.96   
4    10018     5   3/6/2015  3/12/2015    523           2200.00    4799.48   

   Sq_Ft  AvgMonthSales  
0   1183          18000  
1   1183          18000  
2   1183          18000  
3   1183          18000  
4   1183          18000

## Training the model with full dataset

In [11]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X, y)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

## Predict the new result

In [12]:
regressor.predict([[77]])

array([3442.174])

In [13]:
dataset.columns

Index(['StoreID', 'Week', 'Week_start', 'Week_end', 'Count',
       'Sum_Gross Margin', 'Sum_Sales', 'Sq_Ft', 'AvgMonthSales'],
      dtype='object')

In [14]:
pipeline_obj = pipeline.Pipeline([
    ("model", RandomForestRegressor())
])

In [15]:
X = ['Week']
y = ['Sum_Sales']

In [16]:
pipeline_obj.fit(dataset[X],dataset[y])

C:\Users\User\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\pipeline.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)


Pipeline(memory=None,
     steps=[('model', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False))])

In [17]:
pipeline_obj.predict(dataset[X])

array([4288.022, 4270.999, 3907.401, 4337.937, 4823.785, 4465.538,
       3942.938, 4388.348, 4706.306, 4208.19 , 4053.926, 4068.644,
       3501.325, 3777.282, 4706.696, 4807.686, 4904.493, 5540.33 ,
       5124.037, 5327.213, 4831.129, 3751.82 , 3780.98 , 4065.431,
       4621.671, 4203.853, 4643.088, 5054.62 , 4581.598, 4732.42 ,
       4173.715, 3532.079, 4062.623, 3872.751, 3506.651, 4176.777,
       3949.985, 3878.239, 4269.11 , 4495.36 , 4043.206, 4719.211,
       4577.193, 4286.869, 4892.139, 5139.251, 4642.207, 3906.829,
       3972.023, 4096.362, 4394.744, 4755.197, 4357.687, 4746.471,
       5421.264, 5718.858, 5448.698, 5663.978, 4233.386, 3518.618,
       3740.515, 3872.143, 4007.798, 3739.444, 3923.034, 4094.863,
       4845.033, 3963.158, 3476.685, 3454.774, 3582.046, 4176.357,
       4405.719, 3879.296, 3583.992, 3188.03 ])

In [18]:
joblib.dump(pipeline_obj,'RFModelforSales.pickle')

['RFModelforSales.pickle']

In [19]:
modelReload=joblib.load('RFModelforSales.pickle')

In [20]:
modelReload.predict(dataset[X])

array([4288.022, 4270.999, 3907.401, 4337.937, 4823.785, 4465.538,
       3942.938, 4388.348, 4706.306, 4208.19 , 4053.926, 4068.644,
       3501.325, 3777.282, 4706.696, 4807.686, 4904.493, 5540.33 ,
       5124.037, 5327.213, 4831.129, 3751.82 , 3780.98 , 4065.431,
       4621.671, 4203.853, 4643.088, 5054.62 , 4581.598, 4732.42 ,
       4173.715, 3532.079, 4062.623, 3872.751, 3506.651, 4176.777,
       3949.985, 3878.239, 4269.11 , 4495.36 , 4043.206, 4719.211,
       4577.193, 4286.869, 4892.139, 5139.251, 4642.207, 3906.829,
       3972.023, 4096.362, 4394.744, 4755.197, 4357.687, 4746.471,
       5421.264, 5718.858, 5448.698, 5663.978, 4233.386, 3518.618,
       3740.515, 3872.143, 4007.798, 3739.444, 3923.034, 4094.863,
       4845.033, 3963.158, 3476.685, 3454.774, 3582.046, 4176.357,
       4405.719, 3879.296, 3583.992, 3188.03 ])

In [21]:
temp = {}
temp['Week']=77


In [22]:
testDtaa=pd.DataFrame({'x':temp}).transpose()

In [23]:
testDtaa

Week
x    77

In [24]:
modelReload.predict(testDtaa)[0]

3188.0299999999997